name: PR Build
on:
  pull_request:
env: # Fallbacks
  TAG: "latest"
  DOCKERFILE: "Dockerfile-1.14"
jobs:
  latest:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
        env:
          TAG: latest
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-8:
    env:
      TAG: 1.8
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - uses: docker/build-push-action@v1
      with:
        username: bbriggs
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: bbriggs/bukkit
        tags: $TAG
        push: false
  v1-8-3:
    env:
      TAG: 1.8.3
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-8-7:
    env:
      TAG: 1.8.7
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-8-8:
    env:
      TAG: 1.8.8
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-9:
    env:
      TAG: 1.9
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-9-2:
    env:
      TAG: 1.9.2
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-9-4:
    env:
      TAG: 1.9.4
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-10-2:
    env:
      TAG: 1.10.2
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file $DOCKERFILE --tag $TAG
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-11:
    env:
      TAG: 1.11
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-12:
    env:
      TAG: 1.12
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-12-1:
    env:
      TAG: 1.12.1
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-12-2:
    env:
      TAG: 1.12.2
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-13-1:
    env:
      TAG: 1.13.1
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-13-2:
    env:
      TAG: 1.13.2
      DOCKERFILE: "Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-14:
    env:
      TAG: 1.14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-14-1:
    env:
      TAG: 1.14.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-14-2:
    env:
      TAG: 1.14.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-14-3:
    env:
      TAG: 1.14.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-14-4:
    env:
      TAG: 1.14.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-15:
    env:
      TAG: 1.15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-15-1:
    env:
      TAG: 1.15.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-15-2:
    env:
      TAG: 1.15.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-16-1:
    env:
      TAG: 1.16.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
  v1-16-2:
    env:
      TAG: 1.16.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file $DOCKERFILE --tag $TAG
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: bbriggs
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bbriggs/bukkit
          tags: $TAG
          push: false
